name: Build DataDownloader and Push Docker Image

on:
  push:
    branches: [ "paolo/coinbase-downloader" ]

env:
  IMAGE_NAME: paolooranges/coinbase-data-downloader-for-lean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker Get Last Tag
      id: get_version
      run: |
        tags=$(curl -s "https://hub.docker.com/v2/repositories/${IMAGE_NAME}/tags?page_size=100" | jq -r '.results[].name' | grep -v latest | grep -E '^[0-9]+$' | sort -nr)
        if [ -z "$tags" ]; then
          version=1
        else
          version=$(( $(echo "$tags" | head -n1) + 1 ))
        fi
        echo "VERSION=$version" >> $GITHUB_ENV
      env:
        IMAGE_NAME: ${{ env.IMAGE_NAME }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: DockerfileCoinbaseDataDownloader
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{env.VERSION}}, ${{ env.IMAGE_NAME }}:latest
